version: '3.7'

services:

    #AWS S3
    prezo-s3:
        container_name: prezo-s3
        image: minio/minio
        command: server --console-address ":80" /data
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: 12345678
        volumes:
            - prezo-s3:/data
            - /opt/ngrok:/opt/ngrok
            - .:/opt/data
        working_dir: /opt/data
        restart: unless-stopped
        tty: true
        ports:
            - "127.0.1.100:80:80"

    #Redis
    prezo-redis:
        container_name: prezo-redis
        restart: always
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_PASSWORD=123456
            #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
        ports:
            - "127.0.1.101:6379:6379"

    #Meilisearch
    prezo-meilisearch:
        container_name: prezo-meilisearch
        image: getmeili/meilisearch:latest
        restart: always
        environment:
            MEILI_NO_ANALYTICS: "false"
            MEILI_NO_SENTRY: "false"
            MEILI_MASTER_KEY: 123456
        volumes:
            - prezo-meilisearch:/data.ms
        ports:
            - "127.0.1.102:80:7700"

    #MySQL Service 5.7
    prezo-mysql-5.7:
        container_name: prezo-mysql-5.7
        image: mysql:5.7.22
        restart: always
        tty: true
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_DATABASE: prezo
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: develop
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./backups:/opt
            - ./mysql/init-5.7.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql/my-5.7.cnf:/etc/mysql/my.cnf
            - prezo-mysql-5.7:/var/lib/mysql/
        working_dir: /opt
        ports:
            - "127.0.1.103:3306:3306"

    #MySQL Service 8.0
    prezo-mysql-8.0:
        container_name: prezo-mysql-8.0
        image: mysql:8.0.33-debian
        restart: always
        tty: true
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --init-file /docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_DATABASE: ocr
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: develop
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./backups:/opt
            - ./mysql/init-8.0.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mysql/my-8.0.cnf:/etc/mysql/my.cnf
            - prezo-mysql-8.0:/var/lib/mysql/
        working_dir: /opt
        ports:
            - "127.0.1.104:3306:3306"

    #Nginx Api
    prezo-nginx-api:
        container_name: prezo-nginx-api
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ./backups:/var/www/public/backups
            - /opt/ngrok:/opt/ngrok
            - ./sources/api:/var/www
            - ./nginx/api.default.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.1.110:80:80"

    #Nginx Ocr
    prezo-nginx-ocr:
        container_name: prezo-nginx-ocr
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/ocr:/var/www
            - ./nginx/ocr.default.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.1.120:80:80"

    #Nginx Home
    prezo-nginx-home:
        container_name: prezo-nginx-home
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/home:/var/www
            - ./nginx/home.default.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.1.140:80:80"

    #Nginx Panel
    prezo-nginx-panel:
        container_name: prezo-nginx-panel
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/panel:/var/www
            - ./nginx/panel.default.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.1.150:80:80"

    #PHP && APACHE2 App 
    prezo-app:
        container_name: prezo-app
        build:
            args:
                user: develop
                uid: 1000
            context: .
            dockerfile: ./docker_files/Dockerfile.App
        volumes:
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./sources/app:/var/www/html
        restart: unless-stopped
        tty: true
        environment:
            ACTIVE_CRON: 'false'
        ports:
            - "127.0.1.130:80:80"
            - "9040:9040"
        extra_hosts:
            - "api.prezo.box:127.0.1.110"
            - "ocr.prezo.box:127.0.1.120"
        depends_on:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
        links:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-nginx-api
            - prezo-nginx-ocr

    #PHP Ocr
    prezo-ocr:
        container_name: prezo-ocr
        build:
            args:
                user: develop
                uid: 1000
            context: .
            dockerfile: ./docker_files/Dockerfile.Ocr
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/ocr:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - prezo-s3
            - prezo-mysql-8.0
            - prezo-redis
            - prezo-meilisearch
        depends_on:
            - prezo-s3
            - prezo-mysql-8.0
            - prezo-redis
            - prezo-nginx-ocr
            - prezo-meilisearch
        extra_hosts:
            - "hooks.slack.com:54.94.183.148"
            - "prezo-sandbox.s3.eu-west-3.amazonaws.com:52.95.155.64"
        dns:
            - 8.8.8.8
            - 8.8.4.4

    #PHP Api
    prezo-api:
        container_name: prezo-api
        build:
            args:
                user: develop
                uid: 1000
            context: .
            dockerfile: ./docker_files/Dockerfile.Api
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/api:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-meilisearch
        depends_on:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-nginx-api
            - prezo-meilisearch

    #PHP Home
    prezo-home:
        container_name: prezo-home
        build:
            args:
                user: develop
                uid: 1000
            context: .
            dockerfile: ./docker_files/Dockerfile.Home
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/home:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-meilisearch
        depends_on:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-nginx-api
            - prezo-meilisearch

    #PHP Panel
    prezo-panel:
        container_name: prezo-panel
        build:
            args:
                user: develop
                uid: 1000
            context: .
            dockerfile: ./docker_files/Dockerfile.Home
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - /opt/ngrok:/opt/ngrok
            - ./sources/panel:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-meilisearch
        depends_on:
            - prezo-s3
            - prezo-mysql-5.7
            - prezo-redis
            - prezo-nginx-api
            - prezo-meilisearch

    # prezo-grafana:
    #     image: grafana/grafana:8.0.6
    #     container_name: prezo-grafana
    #     restart: unless-stopped
    #     volumes:
    #         - prezo-grafana:/var/lib/grafana
    #     ports:
    #         - "127.0.1.105:3000:3000"

    # prezo-prometheus:
    #     image: prom/prometheus:v2.28.1
    #     container_name: prezo-prometheus
    #     restart: unless-stopped
    #     volumes:
    #         - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #         - prezo-prometheus:/prometheus
    #     ports:
    #         - "127.0.1.106:9090:9090"
    #     command:
    #         - '--config.file=/etc/prometheus/prometheus.yml'
    #         - '--storage.tsdb.path=/prometheus'
    #         - '--storage.tsdb.retention.time=1y'
    #         - '--web.enable-lifecycle'

    # prezo-cadvisor:
    #     image: gcr.io/cadvisor/cadvisor:latest
    #     container_name: prezo-cadvisor
    #     restart: unless-stopped
    #     ports:
    #         - "127.0.1.107:8080:8080"
    #     volumes:
    #         - /:/rootfs:ro
    #         - /var/run:/var/run:rw
    #         - /sys:/sys:ro
    #         - /var/lib/docker/:/var/lib/docker:ro
    #     #   ###### linux
    #     #   # command:
    #     #   # - '--path.rootfs=/host'
    #     #   # pid: host
    #     #   # volumes:
    #     #   # - '/:/host:ro,rslave'

volumes:
    prezo-s3:
        driver: local
    prezo-mysql-5.7:
        driver: local
    prezo-mysql-8.0:
        driver: local
    prezo-meilisearch:
        driver: local
    # prezo-grafana:
    #     driver: local
    # prezo-prometheus:
    #     driver: local
